global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  
  - job_name: short-url 
    static_configs:
      - targets: ['short-url:8080']   # 容器连宿主机
    metrics_path: /metrics
    scrape_interval: 5s